services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - FLASK_ENV=production
    volumes:
      - ~/git/retroboard-v2:/app/database
    networks:
      - retroboard-network
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - retroboard-network
    restart: unless-stopped

networks:
  retroboard-network:
    driver: bridge