name: 'Commit Message Check'
on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
    branches:
      - master

jobs:
  check-commit-message:
    name: Check Commit Message
    runs-on: ubuntu-latest
    steps:
      - name: Check Commit Type
        uses: gsactions/commit-message-checker@v2
        with:
          pattern: '^(?:\w{1,20}: [A-Z]{1}.+$|Merge pull request.*)$'
          flags: 'gm'
          error: 'The first line of the commit message must contain a tag. Check CONTRIBUTING.md for reference.'
          checkAllCommitMessages: 'true'
          accessToken: ${{ secrets.GITHUB_TOKEN }}
          excludeDescription: 'true'
          excludeTitle: 'true'
      - name: Check for fixups
        uses: gsactions/commit-message-checker@v2
        with:
          pattern: '^(?!fixup!).+$'
          flags: 'gm'
          error: 'All fixup commits must be squashed on a pull request.'
          checkAllCommitMessages: 'true'
          accessToken: ${{ secrets.GITHUB_TOKEN }}
          excludeDescription: 'true'
          excludeTitle: 'true'