name: 'Commit Message Check'
on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
    branches:
      - main

jobs:
  check-commit-message:
    name: Check Commit Message
    runs-on: ubuntu-latest
    steps:
      - name: Check Commit Type
        uses: gsactions/commit-message-checker@v2
        with:
          pattern: '\w{0,20}: [A-Z]{1}.+$'
          flags: 'gm'
          error: 'The first line of the commit message must contain a tag. Check CONTRIBUTING.md for reference.'
          checkAllCommitMessages: 'true'
          accessToken: ${{ secrets.GITHUB_TOKEN }}
      - name: Check for fixups
        uses: gsactions/commit-message-checker@v2
        with:
          pattern: 'fixup! .+$'
          error: 'All fixup commits must be squashed on a pull request.'