name: Upload Docker Image On Release

on:
  workflow_dispatch:
  release:
    types: [released]

permissions:
  contents: read
  packages: write

jobs:
  build-and-push:
    name: Build & Push docker image
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'gulyasgergely902' }}
    steps:
      - uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: docker/Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/retroboard:${{ github.ref_name }}