name: Run linter (prettier) on frontend code

on:
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:
    types: 
      - opened
      - reopened
      - synchronize
    branches:
      - master

permissions:
  contents: read

jobs:
  lint:
    name: Lint frontend
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js environment
        uses: actions/setup-node@v3.9.1

      - name: Setup pnpm
        uses: pnpm/action-setup@v4.1.0
        with:
          version: 10.11.0

      - name: Run linting
        run: |
          ./scripts/lint_frontend.sh
