name: Run linter (Ruff) on backend code

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths: [ 'backend/**' ]
  pull_request:
    types: 
      - opened
      - reopened
      - synchronize
    branches: 
      - master
    paths: [ 'backend/**' ]

jobs:
  style-check:
    name: "Lint backend"
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .[dev]
        working-directory: backend

      - name: Run Ruff linting
        run: |
          ./scripts/lint_backend.sh
