name: Run linter (prettier) on frontend code

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    types: 
      - opened
      - reopened
      - synchronize
    branches: 
      - main

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js environment
        uses: actions/setup-node@v3.9.1

      - name: Setup pnpm
        uses: pnpm/action-setup@v4.1.0
        with:
          version: 10.11.0

      - name: Install dependencies
        run: pnpm install

      - name: Run Prettier format check
        run: pnpm format:check
